## Task I
#### Using the data provided, please analyse this data using R or Python and produce a short report, including tables and charts, to highlight which firms should receive the most attention, according to the metrics above.

In [1]:
#importing libraries
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
#getting headers
headers=['Firm_Name',
         'NWP_2016','NWP_2017','NWP_2018','NWP_2019','NWP_2020',
         'SCR_2016','SCR_2017','SCR_2018','SCR_2019','SCR_2020',
         'EOF_SCR_2016','EOF_SCR_2017','EOF_SCR_2018','EOF_SCR_2019','EOF_SCR_2020'
        ,'SCR_Coverage_2016','SCR_Coverage_2017','SCR_Coverage_2018','SCR_Coverage_2019','SCR_Coverage_2020',
         'GWP_2016','GWP_2017','GWP_2018','GWP_2019','GWP_2020',
         'Total_asset_2016','Total_asset_2017','Total_asset_2018','Total_asset_2019','Total_asset_2020',
         'Total_liabilities_2016','Total_liabilities_2017','Total_liabilities_2018','Total_liabilities_2019',
         'Total_liabilities_2020',
         'EOAOL_2016','EOAOL_2017','EOAOL_2018','EOAOL_2019','EOAOL_2020']

In [3]:
#reading file
df=pd.read_excel('/Users/sumakshichauhan/Desktop/Projects/Bank of England/data.xlsx',skiprows=[1])

In [4]:
#setting axis
df1 = df.set_axis(headers, axis=1, inplace=False)
df1.head(5)

,Firm_Name,NWP_2016,NWP_2017,NWP_2018,NWP_2019,NWP_2020,SCR_2016,SCR_2017,SCR_2018,SCR_2019,...,Total_liabilities_2016,Total_liabilities_2017,Total_liabilities_2018,Total_liabilities_2019,Total_liabilities_2020,EOAOL_2016,EOAOL_2017,EOAOL_2018,EOAOL_2019,EOAOL_2020
0,Firm 1,-13779.815629,0.000000,0.000000,0.000000,0.000000,1085.360139,9.635840e-09,0.000000,0.000000,...,69696.557128,0.000000,0.000000,0.000000,0.000000,2031.035937,4.817920,0.000000,0.000000,0.000000
1,Firm 2,28.178059,26.865049,25.064438,23.226445,21.718558,10.190314,1.011357e+01,9.495235,8.146471,...,8.526315,9.585694,8.596011,6.932901,8.526285,33.391180,40.637281,50.621614,57.602326,29.652400
2,Firm 3,0.000000,75.609681,70.578732,78.432782,85.735830,322.955115,3.637823e+02,362.290859,394.295982,...,926.065667,1016.401689,974.733900,1032.497033,1214.913306,583.650604,558.916856,566.073253,598.338699,540.065747
3,Firm 4,22344.199923,23963.910709,25760.390158,25512.748836,24996.021042,16573.644800,1.633275e+04,17103.616000,17219.246080,...,50485.010600,56618.706223,62935.244436,64005.547967,71237.710999,16919.338528,16415.923037,18249.584833,20795.976010,22827.370034
4,Firm 5,68.200993,51.663132,44.010833,42.008556,81.273653,52.824396,3.805377e+01,34.696815,57.231788,...,193.425808,161.417709,118.910867,107.269800,104.922113,148.433518,150.091268,152.205234,142.479147,130.559790

In [5]:
#Removing Outliers(i.e. elcluding firms with no business in the past 5 years)
df2=df1[(df1['GWP_2016']>0) & (df1['GWP_2017']>0) & (df1['GWP_2018']>0) & (df1['GWP_2019']>0)& (df1['GWP_2020']>0)]

In [6]:
#Calculating NWP/GWP ratio for each year 
df2['NWP_GWP_2016']=df2['NWP_2016']/df2['GWP_2016']
df2['NWP_GWP_2017']=df2['NWP_2017']/df2['GWP_2017']
df2['NWP_GWP_2018']=df2['NWP_2018']/df2['GWP_2018']
df2['NWP_GWP_2019']=df2['NWP_2019']/df2['GWP_2019']
df2['NWP_GWP_2020']=df2['NWP_2020']/df2['GWP_2020']

In [7]:
#Replacing null values with 0 for each year 
df2['NWP_GWP_2016']=df2['NWP_GWP_2016'].fillna(0)
df2['NWP_GWP_2017']=df2['NWP_GWP_2017'].fillna(0)
df2['NWP_GWP_2018']=df2['NWP_GWP_2018'].fillna(0)
df2['NWP_GWP_2019']=df2['NWP_GWP_2019'].fillna(0)
df2['NWP_GWP_2020']=df2['NWP_GWP_2020'].fillna(0)

In [8]:
#Calculating average for NWP/GWP ratio, GWP ratio, and EOAOL
df2['NWP_GWP_AVG']=(df2['NWP_GWP_2016']+df2['NWP_GWP_2017']+df2['NWP_GWP_2018']+df2['NWP_GWP_2019']+df2['NWP_GWP_2020'])/5
df2['GWP_AVG']=(df2['GWP_2016']+df2['GWP_2017']+df2['GWP_2018']+df2['GWP_2019']+df2['GWP_2020'])/5
df2['EOAOL_AVG']=(df2['EOAOL_2016']+df2['EOAOL_2017']+df2['EOAOL_2018']+df2['EOAOL_2019']+df2['EOAOL_2020'])/5

In [9]:
#Calculating standard deviation of NWP/GWP ratio for each year
df2['NWP_GWP_2016_AVG']=df2['NWP_2016'].sum()/len(df2['NWP_2016'])
df2['NWP_GWP_2016_SD'] = df2['NWP_GWP_2016']- df2['NWP_GWP_2016_AVG']
df2['NWP_GWP_2017_AVG']=df2['NWP_2017'].sum()/len(df2['NWP_2017'])
df2['NWP_GWP_2017_SD'] = df2['NWP_GWP_2017']- df2['NWP_GWP_2017_AVG']
df2['NWP_GWP_2018_AVG']=df2['NWP_2018'].sum()/len(df2['NWP_2018'])
df2['NWP_GWP_2018_SD'] = df2['NWP_GWP_2018']- df2['NWP_GWP_2018_AVG']
df2['NWP_GWP_2019_AVG']=df2['NWP_2019'].sum()/len(df2['NWP_2019'])
df2['NWP_GWP_2019_SD'] = df2['NWP_GWP_2019']- df2['NWP_GWP_2019_AVG']
df2['NWP_GWP_2020_AVG']=df2['NWP_2020'].sum()/len(df2['NWP_2020'])
df2['NWP_GWP_2020_SD'] = df2['NWP_GWP_2020']- df2['NWP_GWP_2020_AVG']

In [10]:
#Calculating SCR ratio for each year 
df2['SCR_ratio_2016']=df2['EOF_SCR_2016']/df2['SCR_2016']
df2['SCR_ratio_2017']=df2['EOF_SCR_2017']/df2['SCR_2017']
df2['SCR_ratio_2018']=df2['EOF_SCR_2018']/df2['SCR_2018']
df2['SCR_ratio_2019']=df2['EOF_SCR_2019']/df2['SCR_2019']
df2['SCR_ratio_2020']=df2['EOF_SCR_2020']/df2['SCR_2020']

In [11]:
#Replacing null values with 0 for each year 
df2['SCR_ratio_2016']=df2['SCR_ratio_2016'].fillna(0)
df2['SCR_ratio_2017']=df2['SCR_ratio_2017'].fillna(0)
df2['SCR_ratio_2018']=df2['SCR_ratio_2018'].fillna(0)
df2['SCR_ratio_2019']=df2['SCR_ratio_2019'].fillna(0)
df2['SCR_ratio_2020']=df2['SCR_ratio_2020'].fillna(0)
df2['SCR_ratio_AVG']=(df2['SCR_ratio_2016']+df2['SCR_ratio_2017']+df2['SCR_ratio_2018']+df2['SCR_ratio_2019']+df2['SCR_ratio_2020'])/5

In [12]:
df_final= df2[['Firm_Name','GWP_AVG','NWP_GWP_AVG','SCR_ratio_AVG','EOAOL_AVG']]
df_final['NWP_GWP_AVG_STD']=df_final['NWP_GWP_AVG'].std()
df_final['SCR_ratio_AVG_STD']=df_final['SCR_ratio_AVG'].std()
# df_final['NWP_GWP_AVG_STD_Dev']=df_final['NWP_GWP_AVG_STD']-df_final['NWP_GWP_AVG']
# df_final['SCR_ratio_AVG_Dev']=df_final['SCR_ratio_AVG_STD']-df_final['SCR_ratio_AVG']
# df_final['NWP_GWP_AVG_STD']=df_final['NWP_GWP_AVG'].std()

In [13]:
#Keeping those firms who have SCR ratio less than average SCR ratio
df4 = df_final[df_final['SCR_ratio_AVG']<df_final['SCR_ratio_AVG_STD']]

In [14]:
#Keeping those firms who have SCR ratio less than average SCR ratio
df5 = df4[df4['NWP_GWP_AVG']<df4['NWP_GWP_AVG_STD']]

In [15]:
df5.count()

Firm_Name            49
GWP_AVG              49
NWP_GWP_AVG          49
SCR_ratio_AVG        49
EOAOL_AVG            49
NWP_GWP_AVG_STD      49
SCR_ratio_AVG_STD    49
dtype: int64

### Firms which require help immediately

In [16]:
# Selecting top 10 firms having SCR ratio less than 1 i.e. firms which are about to become insolvent.
# Priority order is the GWP i.e.company with more turnover should be given priority
immediate=df5[df5['SCR_ratio_AVG']<1]
immediate.sort_values(by=['GWP_AVG'], ascending=False).head(10)

,Firm_Name,GWP_AVG,NWP_GWP_AVG,SCR_ratio_AVG,EOAOL_AVG,NWP_GWP_AVG_STD,SCR_ratio_AVG_STD
147,Firm 148,60.580624,0.882305,0.999527,182.178579,2.537884,1.535742
212,Firm 213,19.069063,1.000000,0.335523,89.751959,2.537884,1.535742
182,Firm 183,0.002746,1.000000,0.035835,16.890128,2.537884,1.535742

### Firms which require help in short time

In [17]:
# Selecting top 10 firms having NWP/GWP ratio less than 1 i.e. firms which are not insured properly/completely
# Priority order is the GWP i.e.company with more turnover should be given priority
short=df5[df5['NWP_GWP_AVG']<1]
short.sort_values(by=['GWP_AVG'], ascending=False).head(10)

,Firm_Name,GWP_AVG,NWP_GWP_AVG,SCR_ratio_AVG,EOAOL_AVG,NWP_GWP_AVG_STD,SCR_ratio_AVG_STD
3,Firm 4,33857.155951,0.725393,1.476896,19041.638489,2.537884,1.535742
104,Firm 105,14899.454840,0.730077,1.376390,20699.956203,2.537884,1.535742
310,Firm 311,13685.383398,0.393685,1.460739,11662.337006,2.537884,1.535742
198,Firm 199,7590.756243,0.846294,1.136298,2992.774806,2.537884,1.535742
119,Firm 120,3722.156237,0.721322,1.498227,1765.607057,2.537884,1.535742
275,Firm 276,3562.625222,0.735174,1.442752,357.581349,2.537884,1.535742
5,Firm 6,3373.097565,0.768448,1.365511,4062.967891,2.537884,1.535742
321,Firm 322,2188.368694,0.944172,1.417946,2323.824263,2.537884,1.535742
316,Firm 317,2096.439801,0.999999,1.296555,175.940328,2.537884,1.535742
202,Firm 203,1943.019834,0.544558,1.454701,1003.034615,2.537884,1.535742